#global configuration
spring.application.name=api

#Tomcat configuration
server.port=9000

#Log level configuration
logging.level.root=INFO
logging.level.com.exemple=INFO
# logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO

#configuration 
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
# spring.h2.console.settings.web-allow-others=true

# --- Connexion PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/entreprise
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driverClassName=org.postgresql.Driver

# --- JPA / Hibernate ---
# ddl-auto=update : Hibernate crée les tables manquantes automatiquement
spring.jpa.hibernate.ddl-auto=update

# Affiche les requêtes SQL formatées dans le terminal (très utile en cours)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000